# Generated by Django 3.0.5 on 2023-07-25 11:12

import apps.app1.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', djongo.models.fields.EmbeddedField(model_container=apps.app1.models.Book)),
                ('seriesName', models.CharField(max_length=150)),
            ],
        ),
    ]
